name: KnockKnock
version: '${version}'
main: com.minecraftcitiesnetwork.knockknock.KnockKnockPlugin
bootstrapper: com.minecraftcitiesnetwork.knockknock.KnockKnockBootstrap
api-version: '1.21'
description: Allows you to knock on doors, trapdoors, and glass.
author: MinecraftCitiesNetwork, Technofied
permissions:
  knockknock.reload:
    description: Allows reloading KnockKnock configuration.
    default: op
